/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary */

#ifndef _Included_com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary
#define _Included_com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary_init
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary
 * Method:    createInstance
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary_createInstance
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary
 * Method:    preProcess
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary_preProcess
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary
 * Method:    processVoiceInput
 * Signature: (J[BILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary_processVoiceInput
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jstring);

/*
 * Class:     com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary
 * Method:    postProcess
 * Signature: (JLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary_postProcess
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary
 * Method:    getAgeAndSex
 * Signature: ([BILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary_getAgeAndSex
  (JNIEnv *, jobject, jbyteArray, jint, jstring);

/*
 * Class:     com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary
 * Method:    getValidSpeechLength
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary_getValidSpeechLength
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary
 * Method:    compareVoicePrint
 * Signature: (J[BI[BILjava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary_compareVoicePrint
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jbyteArray, jint, jstring);

/*
 * Class:     com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary
 * Method:    updateVoicePrint
 * Signature: (J[BI[BILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary_updateVoicePrint
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jbyteArray, jint, jstring);

/*
 * Class:     com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary
 * Method:    destroyInstance
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary_destroyInstance
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary
 * Method:    unInit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_alibaba_nls_voiceprint_realtime_service_engine_VoicePrintLibrary_unInit
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
